CSHARP/OENIK_PROG3_2019_2_QQ74VD/Project.Web/Models/Character.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Project.Web.Models
{
    public class Character
    {
        [Display(Name = "Character ID")]
        [Required]
        public int Id { get; set; }

        [Display(Name = "Character Name")]
        [Required]
        [StringLength(30,MinimumLength = 3 )]
        public string Name { get; set; }

        [Display(Name = "Character Date of Birth")]
        [Required]
        public DateTime Dob { get; set; }

        [Display(Name = "Character Date of Death")]
        [Required]
        public DateTime Dod { get; set; }

        [Display(Name = "Character Species")]
        [Required]
        public string Species { get; set; }

        [Display(Name = "Character Gender")]
        [Required]
        public string Gender { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_2_QQ74VD/Project.Web/Models/CharactersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Project.Web.Models
{
    public class CharactersViewModel
    {
        public Character EditedChar { get; set; }
        public List<Character> ListOfCharacters { get; set; }
    }
}

CSHARP/OENIK_PROG3_2019_2_QQ74VD/Project.Web/Controllers/CharactersController.cs
using AutoMapper;
using Project.Data;
using Project.Logic;
using Project.Repository;
using Project.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project.Web.Controllers
{
    public class CharactersController : Controller
    {
        CharacterLogic logic;
        IMapper mapper;
        CharactersViewModel vm;

        public CharactersController()
        {
            CharacterRepository repo = new CharacterRepository(new DatabaseEntities7());
            logic = new CharacterLogic(repo);
            mapper = MapperFactory.CreateMapper();

            vm = new CharactersViewModel();
            vm.EditedChar = new Models.Character();
            var chars = logic.GetAll();
            vm.ListOfCharacters = mapper.Map<IEnumerable<Data.Character>, List<Models.Character>>(chars);
        }

        private Models.Character GetCharModel(int id)
        {
            return mapper.Map<Data.Character, Models.Character>(logic.GetById(id));
        }

        // GET: Characters
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("CharactersIndex", vm);
        }

        // GET: Characters/Details/5
        public ActionResult Details(int id)
        {
            return View("CharactersDetails", GetCharModel(id));
        }

        // GET: Characters/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete FAIL";
            if(logic.Delete(id)) TempData["editResult"] = "Delete OK";
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedChar = GetCharModel(id);
            return View("CharactersIndex", vm);

        }
        
        [HttpPost]
        public ActionResult Edit(Models.Character c, string editAction)
        {
            if (ModelState.IsValid && c != null)
            {
                TempData["editResult"] = "Edit OK";
                if(editAction == "AddNew")
                {
                    logic.Add(new Data.Character()
                    {
                        Name = c.Name,
                        Species = c.Species,
                        Dob = c.Dob,
                        Dod = c.Dod,
                        Gender = c.Gender,
                    });
                }
                else
                {
                    bool ret = logic.Update(c.Id, c.Name, c.Gender, c.Species, c.Dob, c.Dod);
                    //if (!ret) TempData["editResult"] = "Edit FAIL";
                }
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedChar = c;
                return View("CharactersIndex", vm);
            }
        }
    }
}

CSHARP/OENIK_PROG3_2019_2_QQ74VD/Project.Web/Views/Characters/CharactersDetails.cshtml
@model Project.Web.Models.Character
@{
    ViewBag.Title = "CharactersDetails";
}

<h2>Data of one character</h2>

@Html.ActionLink("Back to the list page", "Index");

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(x => x.Id)</td>
        <td>@Html.DisplayFor(x => x.Id)</td>

    </tr>
    <tr>
        <td>@Html.DisplayNameFor(x => x.Name)</td>
        <td>@Html.DisplayFor(x => x.Name)</td>

    </tr>
    <tr>
        <td>@Html.DisplayNameFor(x => x.Dob)</td>
        <td>@Html.DisplayFor(x => x.Dob)</td>

    </tr>
    <tr>
        <td>@Html.DisplayNameFor(x => x.Dod)</td>
        <td>@Html.DisplayFor(x => x.Dod)</td>

    </tr>
    <tr>
        <td>@Html.DisplayNameFor(x => x.Species)</td>
        <td>@Html.DisplayFor(x => x.Species)</td>

    </tr>
    <tr>
        <td>@Html.DisplayNameFor(x => x.Gender)</td>
        <td>@Html.DisplayFor(x => x.Gender)</td>

    </tr>
</table>

CSHARP/OENIK_PROG3_2019_2_QQ74VD/Project.Web/Views/Characters/CharactersEdit.cshtml
@model  Project.Web.Models.Character

<h2>Edit a character</h2>

@using (Html.BeginForm("Edit", "Characters"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(x=>x.Id)
    @Html.Hidden("editAction", ViewData["editAction"]?.ToString())

    <div class="editor-label">@Html.LabelFor(x => x.Name)</div>
    <div class="editor-field">@Html.EditorFor(x => x.Name)</div>

    <div class="editor-label">@Html.LabelFor(x => x.Dob)</div>
    <div class="editor-field">@Html.EditorFor(x => x.Dob)</div>

    <div class="editor-label">@Html.LabelFor(x => x.Dod)</div>
    <div class="editor-field">@Html.EditorFor(x => x.Dod)</div>

    <div class="editor-label">@Html.LabelFor(x => x.Species)</div>
    <div class="editor-field">@Html.EditorFor(x => x.Species)</div>

    <div class="editor-label">@Html.LabelFor(x => x.Gender)</div>
    <div class="editor-field">@Html.EditorFor(x => x.Gender)</div>

    <input type="submit" value="SEND" />
}

CSHARP/OENIK_PROG3_2019_2_QQ74VD/Project.Web/Views/Characters/CharactersIndex.cshtml
@model Project.Web.Models.CharactersViewModel
@{
    ViewBag.Title = "CharactersIndex";
}

<h2>My Characters</h2>

<p style="color:red;font-weight:bold">@TempData["editResult"]</p>

@Html.Partial("CharactersEdit", Model.EditedChar)

@Html.Partial("CharactersList", Model.ListOfCharacters)

CSHARP/OENIK_PROG3_2019_2_QQ74VD/Project.Web/Views/Characters/CharactersList.cshtml
@model  IEnumerable<Project.Web.Models.Character>

<h2>List of characters</h2>

@if (Model.Count() == 0)
{
    <p>No data</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(x => x.First().Name)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(x => item.Name)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new {id = item.Id })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new {id = item.Id })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new {id = item.Id })</td>
            </tr>
        }
    </table>
}